version: 2.1
orbs: 
  heroku: circleci/heroku@1.2.6
jobs: 
  build:
    executor: heroku/default
    steps:
      - checkout
      - run:
          command: |
            ls -lrt
            cat /etc/*release
            pwd
    steps:
      - run:
          command: |
            whoami

workflows:
  heroku_deploy:
    jobs:
      - build