version: 2.1
orbs: 
  heroku: circleci/heroku@1.2.6
jobs: 
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          command: |
            pwd
            whoami
            service docker start
      - heroku/install
      - heroku/check-authentication
      - heroku/push-docker-image
      - heroku/release-docker-image


workflows:
  heroku_deploy:
    jobs:
      - deploy