version: 2.1
orbs: 
  heroku: circleci/heroku@1.2.6
jobs: 
  build:
    executor: heroku/default
  steps:
      - checkout
      - heroku/install
      - run:
          command: |
            ls -lrt
            cat /etc/*release
            heroku --version

workflows:
  heroku_deploy:
    jobs:
      - build


